import type { MirrorPresetRecord } from './types';

export const SAMPLE_DATASET: MirrorPresetRecord[] = [
    {
        "id":  "ce-re-01",
        "label":  "ce-re-01",
        "sourceType":  "dataset-entry",
        "role":  "student",
        "roleLabel":  "学员",
        "Y1":  "很像我真实的声音",
        "CE1":  78,
        "CE2":  82,
        "CE3":  74,
        "CE4":  70,
        "RE1":  18,
        "RE2":  24,
        "RE3":  34,
        "RE4":  40,
        "ceTotal":  304,
        "reTotal":  116,
        "ceMean":  76,
        "reMean":  29,
        "status":  "Clear Type",
        "statusBand":  {
                           "ce":  "HIGH",
                           "re":  "LOW"
                       },
        "nearCenterBand":  false
    },
    {
        "id":  "ce-re-02",
        "label":  "ce-re-02",
        "sourceType":  "dataset-entry",
        "role":  "student",
        "roleLabel":  "学员",
        "Y1":  "应该是我，但是音更低",
        "CE1":  68,
        "CE2":  72,
        "CE3":  76,
        "CE4":  64,
        "RE1":  22,
        "RE2":  28,
        "RE3":  32,
        "RE4":  38,
        "ceTotal":  280,
        "reTotal":  120,
        "ceMean":  70,
        "reMean":  30,
        "status":  "Clear Type",
        "statusBand":  {
                           "ce":  "HIGH",
                           "re":  "LOW"
                       },
        "nearCenterBand":  false
    },
    {
        "id":  "ce-re-03",
        "label":  "ce-re-03",
        "sourceType":  "dataset-entry",
        "role":  "student",
        "roleLabel":  "学员",
        "Y1":  "不太像我",
        "CE1":  60,
        "CE2":  66,
        "CE3":  64,
        "CE4":  62,
        "RE1":  40,
        "RE2":  42,
        "RE3":  36,
        "RE4":  38,
        "ceTotal":  252,
        "reTotal":  156,
        "ceMean":  63,
        "reMean":  39,
        "status":  "Clear Type",
        "statusBand":  {
                           "ce":  "HIGH",
                           "re":  "LOW"
                       },
        "nearCenterBand":  false
    },
    {
        "id":  "ce-re-04",
        "label":  "ce-re-04",
        "sourceType":  "dataset-entry",
        "role":  "student",
        "roleLabel":  "学员",
        "Y1":  "很像我真实的声音",
        "CE1":  84,
        "CE2":  78,
        "CE3":  80,
        "CE4":  76,
        "RE1":  26,
        "RE2":  30,
        "RE3":  28,
        "RE4":  34,
        "ceTotal":  318,
        "reTotal":  118,
        "ceMean":  79.5,
        "reMean":  29.5,
        "status":  "Clear Type",
        "statusBand":  {
                           "ce":  "HIGH",
                           "re":  "LOW"
                       },
        "nearCenterBand":  false
    },
    {
        "id":  "ce-re-05",
        "label":  "ce-re-05",
        "sourceType":  "dataset-entry",
        "role":  "organizer",
        "roleLabel":  "组委",
        "Y1":  "应该是我，但是音更低",
        "CE1":  58,
        "CE2":  62,
        "CE3":  60,
        "CE4":  64,
        "RE1":  30,
        "RE2":  32,
        "RE3":  34,
        "RE4":  36,
        "ceTotal":  244,
        "reTotal":  132,
        "ceMean":  61,
        "reMean":  33,
        "status":  "Clear Type",
        "statusBand":  {
                           "ce":  "HIGH",
                           "re":  "LOW"
                       },
        "nearCenterBand":  false
    },
    {
        "id":  "ce-re-06",
        "label":  "ce-re-06",
        "sourceType":  "dataset-entry",
        "role":  "instructor",
        "roleLabel":  "讲师",
        "Y1":  "很像我真实的声音",
        "CE1":  88,
        "CE2":  90,
        "CE3":  84,
        "CE4":  86,
        "RE1":  12,
        "RE2":  18,
        "RE3":  24,
        "RE4":  30,
        "ceTotal":  348,
        "reTotal":  84,
        "ceMean":  87,
        "reMean":  21,
        "status":  "Clear Type",
        "statusBand":  {
                           "ce":  "HIGH",
                           "re":  "LOW"
                       },
        "nearCenterBand":  false
    },
    {
        "id":  "ce-re-07",
        "label":  "ce-re-07",
        "sourceType":  "dataset-entry",
        "role":  "student",
        "roleLabel":  "学员",
        "Y1":  "应该是我，但是音更高",
        "CE1":  72,
        "CE2":  74,
        "CE3":  70,
        "CE4":  68,
        "RE1":  62,
        "RE2":  66,
        "RE3":  64,
        "RE4":  68,
        "ceTotal":  284,
        "reTotal":  260,
        "ceMean":  71,
        "reMean":  65,
        "status":  "Torn Type",
        "statusBand":  {
                           "ce":  "HIGH",
                           "re":  "HIGH"
                       },
        "nearCenterBand":  false
    },
    {
        "id":  "ce-re-08",
        "label":  "ce-re-08",
        "sourceType":  "dataset-entry",
        "role":  "student",
        "roleLabel":  "学员",
        "Y1":  "很像我真实的声音",
        "CE1":  80,
        "CE2":  76,
        "CE3":  78,
        "CE4":  74,
        "RE1":  70,
        "RE2":  72,
        "RE3":  68,
        "RE4":  66,
        "ceTotal":  308,
        "reTotal":  276,
        "ceMean":  77,
        "reMean":  69,
        "status":  "Torn Type",
        "statusBand":  {
                           "ce":  "HIGH",
                           "re":  "HIGH"
                       },
        "nearCenterBand":  false
    },
    {
        "id":  "ce-re-09",
        "label":  "ce-re-09",
        "sourceType":  "dataset-entry",
        "role":  "student",
        "roleLabel":  "学员",
        "Y1":  "应该是我，但是音更高",
        "CE1":  60,
        "CE2":  58,
        "CE3":  62,
        "CE4":  64,
        "RE1":  58,
        "RE2":  60,
        "RE3":  62,
        "RE4":  64,
        "ceTotal":  244,
        "reTotal":  244,
        "ceMean":  61,
        "reMean":  61,
        "status":  "Torn Type",
        "statusBand":  {
                           "ce":  "HIGH",
                           "re":  "HIGH"
                       },
        "nearCenterBand":  false
    },
    {
        "id":  "ce-re-10",
        "label":  "ce-re-10",
        "sourceType":  "dataset-entry",
        "role":  "organizer",
        "roleLabel":  "组委",
        "Y1":  "应该是我，但是音更低",
        "CE1":  92,
        "CE2":  88,
        "CE3":  90,
        "CE4":  86,
        "RE1":  76,
        "RE2":  74,
        "RE3":  72,
        "RE4":  78,
        "ceTotal":  356,
        "reTotal":  300,
        "ceMean":  89,
        "reMean":  75,
        "status":  "Torn Type",
        "statusBand":  {
                           "ce":  "HIGH",
                           "re":  "HIGH"
                       },
        "nearCenterBand":  false
    },
    {
        "id":  "ce-re-11",
        "label":  "ce-re-11",
        "sourceType":  "dataset-entry",
        "role":  "instructor",
        "roleLabel":  "讲师",
        "Y1":  "很像我真实的声音",
        "CE1":  66,
        "CE2":  68,
        "CE3":  70,
        "CE4":  72,
        "RE1":  56,
        "RE2":  58,
        "RE3":  60,
        "RE4":  62,
        "ceTotal":  276,
        "reTotal":  236,
        "ceMean":  69,
        "reMean":  59,
        "status":  "Torn Type",
        "statusBand":  {
                           "ce":  "HIGH",
                           "re":  "HIGH"
                       },
        "nearCenterBand":  false
    },
    {
        "id":  "ce-re-12",
        "label":  "ce-re-12",
        "sourceType":  "dataset-entry",
        "role":  "student",
        "roleLabel":  "学员",
        "Y1":  "不太像我",
        "CE1":  30,
        "CE2":  34,
        "CE3":  38,
        "CE4":  40,
        "RE1":  62,
        "RE2":  66,
        "RE3":  64,
        "RE4":  68,
        "ceTotal":  142,
        "reTotal":  260,
        "ceMean":  35.5,
        "reMean":  65,
        "status":  "Stuck Type",
        "statusBand":  {
                           "ce":  "LOW",
                           "re":  "HIGH"
                       },
        "nearCenterBand":  false
    },
    {
        "id":  "ce-re-13",
        "label":  "ce-re-13",
        "sourceType":  "dataset-entry",
        "role":  "student",
        "roleLabel":  "学员",
        "Y1":  "应该是我，但是音更高",
        "CE1":  20,
        "CE2":  28,
        "CE3":  32,
        "CE4":  36,
        "RE1":  72,
        "RE2":  70,
        "RE3":  68,
        "RE4":  74,
        "ceTotal":  116,
        "reTotal":  284,
        "ceMean":  29,
        "reMean":  71,
        "status":  "Stuck Type",
        "statusBand":  {
                           "ce":  "LOW",
                           "re":  "HIGH"
                       },
        "nearCenterBand":  false
    },
    {
        "id":  "ce-re-14",
        "label":  "ce-re-14",
        "sourceType":  "dataset-entry",
        "role":  "student",
        "roleLabel":  "学员",
        "Y1":  "应该是我，但是音更低",
        "CE1":  40,
        "CE2":  42,
        "CE3":  38,
        "CE4":  44,
        "RE1":  58,
        "RE2":  60,
        "RE3":  56,
        "RE4":  62,
        "ceTotal":  164,
        "reTotal":  236,
        "ceMean":  41,
        "reMean":  59,
        "status":  "Stuck Type",
        "statusBand":  {
                           "ce":  "LOW",
                           "re":  "HIGH"
                       },
        "nearCenterBand":  false
    },
    {
        "id":  "ce-re-15",
        "label":  "ce-re-15",
        "sourceType":  "dataset-entry",
        "role":  "instructor",
        "roleLabel":  "讲师",
        "Y1":  "不太像我",
        "CE1":  10,
        "CE2":  18,
        "CE3":  22,
        "CE4":  26,
        "RE1":  80,
        "RE2":  78,
        "RE3":  82,
        "RE4":  76,
        "ceTotal":  76,
        "reTotal":  316,
        "ceMean":  19,
        "reMean":  79,
        "status":  "Stuck Type",
        "statusBand":  {
                           "ce":  "LOW",
                           "re":  "HIGH"
                       },
        "nearCenterBand":  false
    },
    {
        "id":  "ce-re-16",
        "label":  "ce-re-16",
        "sourceType":  "dataset-entry",
        "role":  "student",
        "roleLabel":  "学员",
        "Y1":  "不太像我",
        "CE1":  22,
        "CE2":  28,
        "CE3":  30,
        "CE4":  34,
        "RE1":  18,
        "RE2":  24,
        "RE3":  22,
        "RE4":  28,
        "ceTotal":  114,
        "reTotal":  92,
        "ceMean":  28.5,
        "reMean":  23,
        "status":  "Paused Type",
        "statusBand":  {
                           "ce":  "LOW",
                           "re":  "LOW"
                       },
        "nearCenterBand":  false
    },
    {
        "id":  "ce-re-17",
        "label":  "ce-re-17",
        "sourceType":  "dataset-entry",
        "role":  "student",
        "roleLabel":  "学员",
        "Y1":  "不太像我",
        "CE1":  40,
        "CE2":  36,
        "CE3":  32,
        "CE4":  28,
        "RE1":  30,
        "RE2":  34,
        "RE3":  38,
        "RE4":  40,
        "ceTotal":  136,
        "reTotal":  142,
        "ceMean":  34,
        "reMean":  35.5,
        "status":  "Paused Type",
        "statusBand":  {
                           "ce":  "LOW",
                           "re":  "LOW"
                       },
        "nearCenterBand":  false
    },
    {
        "id":  "ce-re-18",
        "label":  "ce-re-18",
        "sourceType":  "dataset-entry",
        "role":  "organizer",
        "roleLabel":  "组委",
        "Y1":  "应该是我，但是音更低",
        "CE1":  12,
        "CE2":  20,
        "CE3":  24,
        "CE4":  28,
        "RE1":  14,
        "RE2":  18,
        "RE3":  22,
        "RE4":  26,
        "ceTotal":  84,
        "reTotal":  80,
        "ceMean":  21,
        "reMean":  20,
        "status":  "Paused Type",
        "statusBand":  {
                           "ce":  "LOW",
                           "re":  "LOW"
                       },
        "nearCenterBand":  false
    },
    {
        "id":  "ce-re-19",
        "label":  "ce-re-19",
        "sourceType":  "dataset-entry",
        "role":  "student",
        "roleLabel":  "学员",
        "Y1":  "应该是我，但是音更高",
        "CE1":  48,
        "CE2":  50,
        "CE3":  52,
        "CE4":  54,
        "RE1":  68,
        "RE2":  72,
        "RE3":  70,
        "RE4":  74,
        "ceTotal":  204,
        "reTotal":  284,
        "ceMean":  51,
        "reMean":  71,
        "status":  "Torn Type",
        "statusBand":  {
                           "ce":  "MIDDLE",
                           "re":  "HIGH"
                       },
        "nearCenterBand":  true
    },
    {
        "id":  "ce-re-20",
        "label":  "ce-re-20",
        "sourceType":  "dataset-entry",
        "role":  "instructor",
        "roleLabel":  "讲师",
        "Y1":  "应该是我，但是音更低",
        "CE1":  24,
        "CE2":  28,
        "CE3":  32,
        "CE4":  36,
        "RE1":  46,
        "RE2":  48,
        "RE3":  50,
        "RE4":  52,
        "ceTotal":  120,
        "reTotal":  196,
        "ceMean":  30,
        "reMean":  49,
        "status":  "Paused Type",
        "statusBand":  {
                           "ce":  "LOW",
                           "re":  "MIDDLE"
                       },
        "nearCenterBand":  true
    }
];

export function loadBuiltInSampleDataset(): MirrorPresetRecord[] {
  return SAMPLE_DATASET.map((entry) => ({
    ...entry,
    statusBand: entry.statusBand ? { ...entry.statusBand } : undefined,
  }));
}
